class CoreimpactTasks < Thor
  include Rails.application.config.dradis.thor_helper_module

  namespace "dradis:plugins:coreimpact"

  desc      "upload FILE", "upload CORE Impact results in XML format"
  long_desc "This plugin expect a XML file generated by CORE Impact"
  def upload(file_path)
    require 'config/environment'

    unless File.exists?(file_path)
      $stderr.puts "** the file [#{file_path}] does not exist"
      exit(-1)
    end

    detect_and_set_project_scope

    importer = Dradis::Plugins::Coreimpact::Importer.new(task_options)
    importer.import(file: file_path)
  end

end
